version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --quiet --logpath /dev/null

  user_service:
    build: ./AT20_USER_SERVICE
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:example@mongo:27017/myapp

  admission_service:
    build: ./AT20_ADMISSION_SERVICE/dashboard
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  questionaire_service:
    build: ./AT20_QUESTIONNAIRE_SERVICE/
    ports:
      - '8818:8818'
    environment:
      - PORT = 8818
      - PINO_LOG_LEVEL = info
