version: '3.9'
services:
    compilers:
        container_name: 'dev-at20-compiler-service-container'
        image: at20-compiler-service
        build:
            context: ${PATH_COMPILER_SERVICE}
            dockerfile: dockerfile
        environment:
            - PORT=${PORT_CONTAINER_COMPILER_SERVICE}
        ports:
            - '4000:${PORT_CONTAINER_COMPILER_SERVICE}'
    swagger:
        container_name: at20-swagger-service
        image: at20-swagger-service
        build:
            context: ${PATH_SWAGGER_SERVICE}
            dockerfile: dockerfile
        environment:
            - PORT=${PORT_CONTAINER_SWAGGER_SERVICE}
        ports:
            - '4001:${PORT_CONTAINER_SWAGGER_SERVICE}'
